// Copyright (c) 2026 Intermun. All rights reserved.
// Licensed under the Apache License, Version 2.0 (see LICENSE).

/** Seeded from FWC Evidence Library (SEAMUN I 2027).xlsx — Sheet1, 30 rows. */
export type FwcEvidenceCatalogItem = {
  slug: string;
  category: string;
  title: string;
  startingLocation: string;
  discoverableBy: string;
  tacticalEffect: string;
  isSecret: boolean;
};

export const FWC_EVIDENCE_SOURCE_FILENAME =
  "FWC Evidence Library (SEAMUN I 2027).xlsx";

export const FWC_EVIDENCE_BUNDLED_XLSX_RELATIVE_PATH =
  "lib/fwc/data/fwc-evidence-library.xlsx";

export const FWC_EVIDENCE_LIBRARY_SHEET = "Sheet1";

export const FWC_EVIDENCE_LIBRARY_COLUMNS = [
  "Evidence ID",
  "Category",
  "Item / Description",
  "Primary Location (Grid)",
  "Discoverable By / Requirements",
  "Tactical / Narrative Effect",
] as const;

export const FWC_EVIDENCE_LIBRARY: readonly FwcEvidenceCatalogItem[] = [
  {
    slug: "EVD-01",
    category: "Biological",
    title: "Encapsulated Spore Sample",
    startingLocation: "H3 (Gate Alpha)",
    discoverableBy: "Bio-Hazard Response Equipment",
    tacticalEffect: "Can be analyzed to confirm Upside Down expansion or burned to clear 1 tile.",
    isSecret: false,
  },
  {
    slug: "EVD-02",
    category: "Classified",
    title: "MKUltra Subject Telemetry Log",
    startingLocation: "B3 (Hawkins Lab Sub-Level 3)",
    discoverableBy: "DoE Clearance / Subterranean Infiltration",
    tacticalEffect: "Exposes Brenner's experiments; grants +1 against psychological attacks.",
    isSecret: false,
  },
  {
    slug: "EVD-03",
    category: "Physical",
    title: "Crushed Civilian Vehicle",
    startingLocation: "C6 (Downtown Hawkins)",
    discoverableBy: "HPD Subpoena / Public Investigation",
    tacticalEffect: "Proves physical entity presence; reduces Public Panic meter if covered up.",
    isSecret: false,
  },
  {
    slug: "EVD-04",
    category: "Photographic",
    title: "35mm Photo of Dimensional Portal",
    startingLocation: "B2 (Lab Perimeter)",
    discoverableBy: "Joyce Byers / 35mm Camera",
    tacticalEffect: "Leaking to media triggers Federal Override or cancels active press gag orders.",
    isSecret: false,
  },
  {
    slug: "EVD-05",
    category: "Technical",
    title: "Intercepted Soviet Radio Transcript",
    startingLocation: "J10 (Subterranean Base)",
    discoverableBy: "Radio-Jamming Truck / Broad-Spectrum Array",
    tacticalEffect: "Reveals KGB troop coordinates and portal drill operational status.",
    isSecret: false,
  },
  {
    slug: "EVD-06",
    category: "Audio",
    title: "Tape Recording of Creature Roar",
    startingLocation: "Outer Woods / Field Recon",
    discoverableBy: "Reel-to-Reel Audio Recorder",
    tacticalEffect: "Public release increases Public Panic by +15%; proves non-human entity existence.",
    isSecret: false,
  },
  {
    slug: "EVD-07",
    category: "Biological",
    title: "Corrupted Tendril Vine Segment",
    startingLocation: "H8 (Creel House)",
    discoverableBy: "Flamethrower Ordnance / Thermal Unit",
    tacticalEffect: "Identifies thermal vulnerabilities; reveals Hive Mind communication channels.",
    isSecret: false,
  },
  {
    slug: "EVD-08",
    category: "Document",
    title: "Unmarked Wiretap Log Sheet",
    startingLocation: "B8 (Police Dept)",
    discoverableBy: "Connie Frazier / HPD Intercept",
    tacticalEffect: "Exposes character communication networks and secret backroom pacts.",
    isSecret: false,
  },
  {
    slug: "EVD-09",
    category: "Physical",
    title: "Forged U.S. Identification Papers",
    startingLocation: "Off-Grid Hideout / Getaway Van",
    discoverableBy: "Kali Prasad / KGB Infiltration Units",
    tacticalEffect: "Proves foreign or rogue vigilante presence inside municipal borders.",
    isSecret: false,
  },
  {
    slug: "EVD-10",
    category: "Chemical",
    title: "MKUltra Clinical Sedative Vials",
    startingLocation: "B3 (Lab Isolation Unit)",
    discoverableBy: "Brenner / Sam Owens / Infiltration Heist",
    tacticalEffect: "Suppresses psychokinetic abilities or shields delegates from mind links.",
    isSecret: false,
  },
  {
    slug: "EVD-11",
    category: "Technical",
    title: "Analog Wall-of-Lights Frequency Log",
    startingLocation: "D12 (Byers House)",
    discoverableBy: "Joyce Byers / HAM Radio Operator",
    tacticalEffect: "Detects dimensional rift activity 1 cycle before a major gate opening.",
    isSecret: false,
  },
  {
    slug: "EVD-12",
    category: "Military",
    title: "Scorched Shell Casing & Burn Pattern",
    startingLocation: "K6 (Decayed Bradley's)",
    discoverableBy: "Jack Sullivan / HPD Crime Scene Unit",
    tacticalEffect: "Proves deployment of heavy military ordnance in civilian sectors.",
    isSecret: false,
  },
  {
    slug: "EVD-13",
    category: "Biological",
    title: "Molted Demogorgon Skin Husk",
    startingLocation: "H2 (Gate Alpha Perimeter)",
    discoverableBy: "Field Search / Bio-Hazard Kit",
    tacticalEffect: "Confirms entity growth stage; grants +1 tracking accuracy against packs.",
    isSecret: false,
  },
  {
    slug: "EVD-14",
    category: "Audio",
    title: "Encrypted Russian Transceiver Tape",
    startingLocation: "J11 (Starcourt Sub-Level)",
    discoverableBy: "HPD Subpoena / Intercept Directive",
    tacticalEffect: "Proves subterranean foreign presence beneath commercial infrastructure.",
    isSecret: false,
  },
  {
    slug: "EVD-15",
    category: "Document",
    title: "Signed DoE Media Gag Order",
    startingLocation: "C6 (Hawkins Post Office)",
    discoverableBy: "Connie Frazier / Investigative Journalist",
    tacticalEffect: "Suppresses public news releases; delays Public Panic increases by 2 cycles.",
    isSecret: false,
  },
  {
    slug: "EVD-16",
    category: "Technical",
    title: "Overclocked Portal Drill Blueprint",
    startingLocation: "J10 (Subterranean Facility)",
    discoverableBy: "Sabotage Unit / Infiltration Directive",
    tacticalEffect: "Allows engineers to disable or overload Soviet portal machinery.",
    isSecret: false,
  },
  {
    slug: "EVD-17",
    category: "Physical",
    title: "Broken Subterranean Elevator Keycard",
    startingLocation: "D10 (Starcourt Mall)",
    discoverableBy: "Physical Search / Security Seizure",
    tacticalEffect: "Unlocks direct surface access to secret Soviet subterranean complexes.",
    isSecret: false,
  },
  {
    slug: "EVD-18",
    category: "Biological",
    title: "Toxic Spore Cloud Air Filter",
    startingLocation: "H3 (Spore Vector Zone)",
    discoverableBy: "Dr. Sam Owens / Bio Burn Unit",
    tacticalEffect: "Accelerates development of medical shielding against atmospheric contagion.",
    isSecret: false,
  },
  {
    slug: "EVD-19",
    category: "Photographic",
    title: "Polaroid of Vecna Mindscape Victim",
    startingLocation: "H8 (Creel House Perimeter)",
    discoverableBy: "35mm Camera / Field Recon",
    tacticalEffect: "Confirms Vecna's psychic curse pattern; unlocks psychological triage option.",
    isSecret: false,
  },
  {
    slug: "EVD-20",
    category: "Document",
    title: "Confidential Autopsy Report",
    startingLocation: "B8 (HPD Morgue)",
    discoverableBy: "Chief Jim Hopper / Coroner Access",
    tacticalEffect: "Proves internal organ rupture caused by non-conventional physical forces.",
    isSecret: false,
  },
  {
    slug: "EVD-21",
    category: "Chemical",
    title: "High-Purity Industrial Salt Container",
    startingLocation: "D12 (Byers Residence)",
    discoverableBy: "Eleven / Joyce Byers",
    tacticalEffect: "Required fuel asset to build a makeshift sensory deprivation tank.",
    isSecret: false,
  },
  {
    slug: "EVD-22",
    category: "Technical",
    title: "Scrambled CB Radio Transceiver",
    startingLocation: "F8 (Outer Woods Relay Tower)",
    discoverableBy: "Kali Prasad / Civilian HAM Operator",
    tacticalEffect: "Intercepts military and police emergency frequency broadcasts.",
    isSecret: false,
  },
  {
    slug: "EVD-23",
    category: "Physical",
    title: "Severed Biological Tendril Claw",
    startingLocation: "G6 (Rift Boundary Line)",
    discoverableBy: "Field Combat / Military Ordnance",
    tacticalEffect: "Proves interdimensional organism penetration into Normal Hawkins sectors.",
    isSecret: false,
  },
  {
    slug: "EVD-24",
    category: "Document",
    title: "Military Martial Law Lockdown Order",
    startingLocation: "Mobile Command Base",
    discoverableBy: "Lt. Colonel Jack Sullivan",
    tacticalEffect: "Authorizes APC roadblocks and media blackouts across town sectors.",
    isSecret: false,
  },
  {
    slug: "EVD-25",
    category: "Biological",
    title: "Corrupted Soil & Groundwater Sample",
    startingLocation: "C11 (Lover's Lake)",
    discoverableBy: "Soil Sampling Kit / Field Analysis",
    tacticalEffect: "Proves spreading biological contamination in municipal water supplies.",
    isSecret: false,
  },
  {
    slug: "EVD-26",
    category: "Document",
    title: "Classified Executive Immunity Decree",
    startingLocation: "Washington Dispatch / Field Unit",
    discoverableBy: "Dr. Martin Brenner",
    tacticalEffect: "Nullifies local law enforcement arrest warrants or legal subpoenas.",
    isSecret: false,
  },
  {
    slug: "EVD-27",
    category: "Physical",
    title: "Smashed Rotary Telephone",
    startingLocation: "A11 (Wheeler Residence)",
    discoverableBy: "HPD Investigation / Physical Search",
    tacticalEffect: "Confirms localized electromagnetic surge caused by psychokinetic discharge.",
    isSecret: false,
  },
  {
    slug: "EVD-28",
    category: "Technical",
    title: "Portable Electro-Magnetic Compass",
    startingLocation: "B2 (Lab Gate Perimeter)",
    discoverableBy: "Analog Scouting / Field Recon",
    tacticalEffect: "Tracks regional magnetic distortion to locate hidden active rifts.",
    isSecret: false,
  },
  {
    slug: "EVD-29",
    category: "Photographic",
    title: "Aerial Reconnaissance Map of Rifts",
    startingLocation: "Perimeter Checkpoint",
    discoverableBy: "U.S. Military Recon / Recon Drone",
    tacticalEffect: "Pinpoints exact coordinates of widening dimensional boundary tears.",
    isSecret: false,
  },
  {
    slug: "EVD-30",
    category: "Document",
    title: "Starcourt Mall Sub-Level Structural Blueprint",
    startingLocation: "C6 (Hawkins Town Hall)",
    discoverableBy: "Municipal Subpoena / Infiltration Heist",
    tacticalEffect: "Reveals hidden ventilation shafts bypasses into subterranean bases.",
    isSecret: false,
  },
];

